name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Checks out the repository this file is in
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t stepanklos/lightning_map:latest .

    - name: Dockerhub login
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

    -name: Push image into Dockerhub
      run: docker push stepanklos/lightning_map:latest